version: "3"

services:
  jupyterlab:
    build:
        context: .
        dockerfile: ./docker/dockerfile.jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./src/notebooks:/opt/app/notebooks
      - ./src/data:/opt/app/data
    entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/opt/app/notebooks --allow-root'
  
  minio-server:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./src/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}

  # docker run \
  #  -p 9000:9000 \
  #  -p 9090:9090 \
  #  --user $(id -u):$(id -g) \
  #  --name minio1 \
  #  -e "MINIO_ROOT_USER=ROOTUSER" \
  #  -e "MINIO_ROOT_PASSWORD=CHANGEME123" \
  #  -v ${HOME}/minio/data:/data \
  #  quay.io/minio/minio server /data --console-address ":9090"