version: "3"

services:
  jupyterlab:
    build:
        context: .
        dockerfile: ./docker/dockerfile.jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./src/notebooks:/opt/app/notebooks
      - ./src/data:/opt/app/data
    entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/opt/app/notebooks --allow-root'